# ══════════════════════════════════════════════════════
# ROFI — ${THEME_SLUG}.rasi
# ══════════════════════════════════════════════════════

# ── Deploy helpers (rofi owns its own deployment) ─────

_rofi_ensure_dir() {
    local dir="$1"
    if $DRY_RUN; then
        echo "  [DRY RUN] Would ensure dir: $dir"
        return
    fi
    if [[ ! -d "$dir" ]]; then
        mkdir -p "$dir"
        echo "  ✓ Created dir: $dir"
    fi
}

_rofi_make_link() {
    local link="$1"
    local target="$2"
    if $DRY_RUN; then
        echo "  [DRY RUN] Would symlink: $link → $target"
        return
    fi
    if [[ -L "$link" || -e "$link" ]]; then
        rm -f "$link"
    fi
    ln -s "$target" "$link"
    echo "  ✓ Symlinked: $link → $target"
}

_rofi_write_config() {
    local config_file="$ROFI_CONFIG_DIR/config.rasi"
    if [[ -f "$config_file" ]] && grep -q "active.rasi" "$config_file" 2>/dev/null; then
        echo "  ✓ rofi config.rasi already up to date"
        return
    fi
    local content='/**
 * Rofi config
 * AUTO-GENERATED by rofi.sh — do not edit manually.
 * Theme is controlled via active.rasi symlink.
 **/

@theme "'"$ROFI_CONFIG_DIR/active.rasi"'"'
    if $DRY_RUN; then
        echo "  [DRY RUN] Would write: $config_file"
        return
    fi
    printf '%s\n' "$content" > "$config_file"
    echo "  ✓ Wrote rofi config.rasi"
}

# ── Generate theme file ────────────────────────────────

write_file "rofi/${THEME_SLUG}.rasi" \
"/**
 * Author : Pablo Iván
 * Github : @pabloivan
 * Rofi Theme File — $THEME_NAME
 * Rofi Version: 1.7.3
 *
 * AUTO-GENERATED — do not edit manually.
 * Edit ${THEME_SLUG}.conf and re-run generate.sh
 **/

/*****----- Configuration -----*****/
configuration {
    modi:                        \"drun,filebrowser,window\";
    show-icons:                  true;
    display-drun:                \"Apps\";
    display-run:                 \"Run\";
    display-filebrowser:         \"Files\";
    display-window:              \"Windows\";
    drun-display-format:         \"{name}\n[<span weight='light' size='small'><i>({generic})</i></span>]\";
    window-format:               \"Class : {c}\nWorkspace : {w}\";
}

/*****----- Global Properties -----*****/
* {
    font:            \"Iosevka Nerd Font 10\";

    bg0:             #$BG0;
    bg1:             #$BG1;
    bg2:             #$BG2;
    bg3:             #$BG3;

    fg0:             #$FG0;
    fg1:             #$FG1;

    accent0:         #$ACCENT0;
    accent1:         #$ACCENT1;
    accent2:         #$ACCENT2;
    accent-sec:      #$ACCENT_SEC;

    red:             #$RED;

    light-contrast:  #$ROFI_LIGHT_CONTRAST;
    entry-bg:        rgba($ROFI_ENTRY_BG);

    background-color: transparent;
    text-color:       #$FG0;
}

/*****----- Main Window -----*****/
window {
    transparency:                \"real\";
    location:                    center;
    anchor:                      center;
    fullscreen:                  false;
    width:                       500px;
    x-offset:                    0px;
    y-offset:                    0px;

    enabled:                     true;
    margin:                      0px;
    padding:                     0px;
    border:                      2px solid;
    border-color:                @accent1;
    border-radius:               12px;
    cursor:                      \"default\";
    background-color:            @bg0;
}

/*****----- Main Box -----*****/
mainbox {
    enabled:                     true;
    spacing:                     15px;
    padding:                     30px;
    background-color:            transparent;
    children:                    [ \"inputbar\", \"mode-switcher\", \"listview\" ];
}

/*****----- Inputbar -----*****/
inputbar {
    enabled:                     true;
    spacing:                     15px;
    margin:                      0px;
    background-color:            transparent;
    children:                    [ \"textbox-prompt-colon\", \"entry\" ];
}

textbox-prompt-colon {
    enabled:                     true;
    expand:                      false;
    padding:                     12px 16px;
    border:                      0px;
    border-radius:               10px;
    background-color:            @accent1;
    text-color:                  @light-contrast;
    str:                         \"󰈊\";
}

entry {
    enabled:                     true;
    padding:                     12px 16px;
    border:                      0px;
    border-radius:               10px;
    background-color:            @entry-bg;
    text-color:                  @fg0;
    cursor:                      text;
    placeholder:                 \"$ROFI_PLACEHOLDER\";
    placeholder-color:           @accent2;
    vertical-align:              0.5;
    horizontal-align:            0.0;
}

/*****----- Listview -----*****/
listview {
    enabled:                     true;
    columns:                     1;
    lines:                       5;
    cycle:                       true;
    dynamic:                     true;
    scrollbar:                   false;
    layout:                      vertical;
    reverse:                     false;
    fixed-height:                true;
    fixed-columns:               true;

    spacing:                     10px;
    background-color:            transparent;
    cursor:                      \"default\";
}

/*****----- Elements -----*****/
element {
    enabled:                     true;
    spacing:                     10px;
    margin:                      0px;
    padding:                     10px;
    border:                      0px solid;
    border-radius:               10px;
    background-color:            transparent;
    text-color:                  @fg0;
    cursor:                      pointer;
}

element normal.active {
    background-image:            linear-gradient(to right, #$ROFI_GRAD_DARK, #$ACCENT1);
    text-color:                  @light-contrast;
}

element selected.normal {
    border-radius:               10px;
    background-image:            linear-gradient(to right, #$ACCENT1, #$ACCENT2);
    text-color:                  @bg0;
}

element selected.active {
    background-image:            linear-gradient(to right, #$ROFI_GRAD_DARKER, #$ROFI_GRAD_DARK);
    text-color:                  @light-contrast;
}

element-icon {
    background-color:            transparent;
    size:                        48px;
    cursor:                      inherit;
}

element-text {
    background-color:            inherit;
    text-color:                  inherit;
    cursor:                      inherit;
    vertical-align:              0.5;
    horizontal-align:            0.0;
}

/*****----- Mode Switcher -----*****/
mode-switcher {
    enabled:                     true;
    expand:                      false;
    spacing:                     15px;
    background-color:            transparent;
}

button {
    font:                        \"Iosevka Nerd Font Bold 10\";
    padding:                     10px;
    border-radius:               10px;
    background-color:            @accent1;
    text-color:                  @fg0;
    cursor:                      pointer;
}

button selected {
    background-color:            @accent2;
    text-color:                  @bg0;
}

/*****----- Message -----*****/
error-message {
    padding:                     20px;
    background-color:            @bg0;
    text-color:                  @red;
}

textbox {
    padding:                     0px;
    border-radius:               0px;
    text-color:                  @fg0;
    vertical-align:              0.5;
    horizontal-align:            0.0;
}"

# ── Deploy ─────────────────────────────────────────────
ROFI_CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/rofi"

_rofi_ensure_dir "$ROFI_CONFIG_DIR"
_rofi_make_link \
    "$ROFI_CONFIG_DIR/active.rasi" \
    "$THEME_OUTPUT_DIR/rofi/${THEME_SLUG}.rasi"
_rofi_write_config