input {
    kb_layout = es
    repeat_rate = 50
    repeat_delay = 240

    touchpad {
        natural_scroll = true
        tap-to-click = true
        middle_button_emulation = true
        disable_while_typing = false
    }
}