# ----------------------------------------------------- 
# Terminal and Essentials
# ----------------------------------------------------- 
bind = $mainMod, Return, exec, $term
bind = $mainMod, Q, killactive,
bind = $mainMod ALT, Q, exit, 
bind = $mainMod, D, exec, rofi -show drun
bind = $mainMod, C, exec, pkill -x nwg-dock-hyprla || nwg-dock-hyprland -i 48 -p bottom -a center -r -c "rofi -show drun"
bind = $mainMod CTRL, W, exec, ~/.config/hypr/scripts/execwaybar.sh
bind = $mainMod CTRL, A, exec, ~/Themes/generate.sh
bind = $mainMod CTRL, S, exec, bash ~/Themes/switch-theme.sh 
bind = $mainMod CTRL, V, exec, bash ~/.config/hypr/scripts/altavoces.sh
bind = $mainMod CTRL, N, exec, bash ~/.config/hypr/scripts/doqaus.sh

# Power menu and Lock
bind = ALT, Q, exec, ~/.config/hypr/scripts/powermenu.sh 
bind = $mainMod, L, exec, swaylock

# Quick Application Shortcuts
bind = $mainMod, B, exec, $browser
bind = $mainMod CTRL, E, exec, $fmgr
bind = $mainMod, E, exec, kitty -e yazi
bind = $mainMod, R, exec, ~/Documentos/comercio_exterior_bienes/rstudio-pixi.sh
bind = $mainMod, W, exec, code
bind = $mainMod, T, exec, MOZ_ENABLE_WAYLAND=1 ~/Apps/tor-browser/Browser/start-tor-browser

# ----------------------------------------------------- 
# Workspace Navigation
# ----------------------------------------------------- 
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# ----------------------------------------------------- 
# Move Active Window to Workspace
# ----------------------------------------------------- 
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

# ----------------------------------------------------- 
# Window Management
# ----------------------------------------------------- 
bind = $mainMod, F, fullscreen,
bind = $mainMod, Space, togglefloating, 
bind = $mainMod SHIFT, Space, togglefloating, 

# Move Focus (Arrows)
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

bind = $mainMod, Tab, exec, ~/.config/hypr/scripts/cycle-windows.sh prev
bind = ALT, Tab, exec, ~/.config/hypr/scripts/cycle-windows.sh

# ----------------------------------------------------- 
# Screenshots
# ----------------------------------------------------- 
bind = , Print, exec, grim ~/Imagenes/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png
bind = $mainMod, J, exec, grim -g "$(slurp)" /tmp/screenshot.png && gthumb /tmp/screenshot.png
bind = $mainMod, I, exec, grim -g "$(slurp)" - | wl-copy
# ----------------------------------------------------- 
# Screenshots
# ----------------------------------------------------- 
bind = $mainMod, H, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy