# 05-appearance.conf
general {
    gaps_in = 3
    gaps_out = 1
    border_size = 1
    col.active_border = rgba(33ccffee)
}

misc {
    force_default_wallpaper = 0    
    disable_hyprland_logo = true   
}

# Source your generated colors
source = ~/Themes/generated/active/hypr/colors.conf