### MONITOR AND WORKSPACE CONFIGURATION (2K DESKTOP)
## Monitor Setup: Left Monitor (DP-3), Right Monitor (DP-2)
# Scale 1
#monitor = DP-3, 2560x1440@180, 0x0, 1
#monitor = DP-2, 2560x1440@180, 2560x0, 1

# Scale 1.5
monitor = DP-3, 2560x1440@180, 0x0, 1.6
monitor = DP-2, 2560x1440@180, 1600x0, 1.6

## Workspace Assignments
# Workspaces 1-5 assigned to the Left Monitor (DP-2)
workspace = 1, monitor:DP-2
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

# Workspaces 6-10 assigned to the Right Monitor (DP-3)
workspace = 6, monitor:DP-3
workspace = 7, monitor:DP-3
workspace = 8, monitor:DP-3
workspace = 9, monitor:DP-3
workspace = 10, monitor:DP-3