# Launch Waybar
#exec-once = ~/.config/hypr/scripts/execwaybar.sh 
exec-once = waybar

# Notification Daemon
exec-once = dunst 

# Removable Media Automounte
exec-once = udiskie --smart-tray --notify
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1

# Wallpaper
exec-once = hyprpaper
exec-once = sleep 2 && hyprctl hyprpaper wallpaper ",/home/pivan/Themes/wallpapers/active"

#Cliphist
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store