# 0. Environment
source = ~/.config/hypr/conf.d/00-environment.conf

# 1. Variables
source = ~/.config/hypr/conf.d/01-variables.conf

# 2. Input
source = ~/.config/hypr/conf.d/02-input.conf

# 3. Keybindings
source = ~/.config/hypr/conf.d/03-binds.conf

# 4. Mouse
source = ~/.config/hypr/conf.d/04-mouse.conf

# 5. Appearance
source = ~/.config/hypr/conf.d/05-appearance.conf

# 6. Monitors and Workspaces
source = ~/.config/hypr/conf.d/06-monitors.conf

# 7. Startup
source = ~/.config/hypr/conf.d/07-startup.conf
